import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import I18nProvider from "@/components/I18nProvider";
import { getResources } from "../../i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const resources = getResources();

  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <I18nProvider locale={params.locale} resources={resources}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}